files:
  - source: translation/en/dictionary.json
    translation: /translation/%locale%/dictionary.json
    update_option: update_as_unapproved
  - source: translation/en/en.json
    translation: /translation/%locale%/%locale%.json
    update_option: update_as_unapproved
  - source: translation/en/re-en.json
    translation: /translation/%locale%/re-%locale%.json
    update_option: update_as_unapproved
  - source: translation/en/action-en.json
    translation: /translation/%locale%/action-%locale%.json
    update_option: update_as_unapproved
  - source: translation/en/kingmaker-en.json
    translation: /translation/%locale%/kingmaker-%locale%.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/*.json
    ignore:
      - equipment.json
      - feats.json
      - spells.json
      - actions.json
      - macros.json
      - conditions.json
      - fall-of-plaguestone.json
    translation: /translation/%locale%/compendium/pf2e.%file_name%.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/feats.json
    translation: /translation/%locale%/compendium/pf2e.%file_name%-srd.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/equipment.json
    translation: /translation/%locale%/compendium/pf2e.%file_name%-srd.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/spells.json
    translation: /translation/%locale%/compendium/pf2e.%file_name%-srd.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/actions.json
    translation: /translation/%locale%/compendium/pf2e.%file_name%pf2e.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/macros.json
    translation: /translation/%locale%/compendium/pf2e.pf2e-%file_name%.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/conditions.json
    translation: /translation/%locale%/compendium/pf2e.conditionitems.json
    update_option: update_as_unapproved
  - source: translation/en/compendium/fall-of-plaguestone.json
    translation: /translation/%locale%/compendium/pf2e.fall-of-plaguestone-bestiary.json
    update_option: update_as_unapproved